name: dart2_constant
version: 1.0.0+dart2
description: A polyfill for Dart 2 constant names.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dart2_constants

environment:
  sdk: '>=2.0.0-dev.34.0 <3.0.0'

dev_dependencies:
  args: "^1.0.0"
  analyzer: ">=0.30.0 <0.33.0"
  dart_style: "^1.0.0"
  path: "^1.0.0"
